swipe:
  3:
    begin:
      command: YDOTOOL_SOCKET="$HOME/.ydotool_socket" ydotool click 0x40
    update:
      command: YDOTOOL_SOCKET="$HOME/.ydotool_socket" ydotool mousemove -- $move_x, $move_y
      interval: 0.01
      accel: 2
    end:
      command: YDOTOOL_SOCKET="$HOME/.ydotool_socket" ydotool click 0x80
  4:
    left:
      command: YDOTOOL_SOCKET="$HOME/.ydotool_socket" ydotool key 56:1 key 106:1 key 106:0 key 56:0
    right:
      command: YDOTOOL_SOCKET="$HOME/.ydotool_socket" ydotool key 56:1 key 105:1 key 105:0 key 56:0 
