[options]
IgnorePkg = ollama ollama-rocm
HoldPkg     = pacman glibc
Architecture = auto

Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
DownloadUser = alpm
ILoveCandy

SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

