[colors.bright]
black = "#727072"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[colors.normal]
black = "#000000"
blue = "#FC9867"
cyan = "#78DCE8"
green = "#A9DC76"
magenta = "#AB9DF2"
red = "#FF6188"
white = "#FCFCFA"
yellow = "#FFD866"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 4

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[scrolling]
history = 5000

[window]
dynamic_padding = true
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
